stages:
  - test
  - build
  - deploy

tests-stage:
  stage: test
  image: djgirls
  script:
    - python manage.py test --noinput
  tags:
    - docker

build-stage:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} .
    - docker ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
  when: manual
  tags:
    - docker

deploy-stage:
  stage: deploy
  script:
    - echo "Deploying process..."
  tags:
    - docker

